apiVersion: v1
kind: Service
metadata:
  labels:
    app: wconsole-client 
  name: wconsole-client
  namespace: cloudone 
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wconsole-client 
  sessionAffinity: None
  type: NodePort
